### ISSUE TITLE
Does this tool detect the words "segregating", "black", "white", "slavery", "mastery"

### ISSUE THREAD

**Issue by jagadeeshnv** [dell/common-github-actions#43]
### How can the Team help you today?

The file "all-words.txt" does not have the following words.

**Details: ?**

"segregating" - This is a variation, not listed in your
"black" - black alone is also not listed
"white" - white alone is also not listed
"slavery" - Variation
"mastery" - variation

and may be more like these.

**Comment by gallacher** [comment]
@jagadeeshnv, thank you for reaching out with your question.  We are currently investigating ways to enhance the GitHub action so that users can provide their own list of non-inclusive words rather than being tied to the list currently provided.  We welcome any contributions you may be able to provide to help make this happen.
